# Generated by Django 4.2.2 on 2024-07-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reclamation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reclamation',
            table='reclamation',
        ),
    ]
