# Generated by Django 4.2.2 on 2024-04-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_expiration',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_event',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='lien',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='secteur',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
