# Generated by Django 4.2.2 on 2024-04-26 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_event_date_expiration_event_description_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='set_reminder',
        ),
    ]
