# Generated by Django 4.2.2 on 2024-05-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_remove_event_set_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
    ]
