# Generated by Django 4.2.2 on 2024-06-14 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0006_event_is_active_event_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='secteur',
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='Event.secteur')),
            ],
            options={
                'db_table': 'secteur',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='secteur',
            field=models.ManyToManyField(to='Event.secteur'),
        ),
    ]
