# Generated by Django 4.2.2 on 2024-03-19 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0003_delete_hello'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploiPlus',
            fields=[
                ('emploi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emploi.emploi')),
                ('status', models.CharField(choices=[('Emploi', 'Emploi'), ('Mission', 'Mission')], max_length=10)),
                ('nbr_candidature_max', models.IntegerField()),
                ('heure_debut', models.DateTimeField()),
                ('heure_fin', models.DateTimeField()),
                ('type_postulation', models.CharField(max_length=100)),
                ('closure', models.BooleanField()),
            ],
            bases=('emploi.emploi',),
        ),
    ]
