# Generated by Django 4.2.2 on 2024-04-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0004_emploiplus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploiplus',
            name='heure_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emploiplus',
            name='heure_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emploiplus',
            name='nbr_candidature_max',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
