# Generated by Django 4.2.2 on 2024-04-14 21:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emploi', '0007_favoris'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoris',
            old_name='utilisateur',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='favoris',
            unique_together={('user', 'emploi')},
        ),
    ]
